#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Vijaycs85\GameTxt\Command\GameCommand;

$application = new Application();
$application->add(new GameCommand());
$application->run();